// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Eatinghistory is the predicate function for eatinghistory builders.
type Eatinghistory func(*sql.Selector)

// Foodmenu is the predicate function for foodmenu builders.
type Foodmenu func(*sql.Selector)

// Mealplan is the predicate function for mealplan builders.
type Mealplan func(*sql.Selector)

// Taste is the predicate function for taste builders.
type Taste func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
