// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sync"
	"time"

	"github.com/Teeth/app/ent/eatinghistory"
	"github.com/Teeth/app/ent/foodmenu"
	"github.com/Teeth/app/ent/mealplan"
	"github.com/Teeth/app/ent/taste"
	"github.com/Teeth/app/ent/user"

	"github.com/facebookincubator/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEatinghistory = "Eatinghistory"
	TypeFoodmenu      = "Foodmenu"
	TypeMealplan      = "Mealplan"
	TypeTaste         = "Taste"
	TypeUser          = "User"
)

// EatinghistoryMutation represents an operation that mutate the Eatinghistories
// nodes in the graph.
type EatinghistoryMutation struct {
	config
	op              Op
	typ             string
	id              *int
	added_time      *time.Time
	clearedFields   map[string]struct{}
	foodmenu        *int
	clearedfoodmenu bool
	mealplan        *int
	clearedmealplan bool
	taste           *int
	clearedtaste    bool
	user            *int
	cleareduser     bool
	done            bool
	oldValue        func(context.Context) (*Eatinghistory, error)
}

var _ ent.Mutation = (*EatinghistoryMutation)(nil)

// eatinghistoryOption allows to manage the mutation configuration using functional options.
type eatinghistoryOption func(*EatinghistoryMutation)

// newEatinghistoryMutation creates new mutation for $n.Name.
func newEatinghistoryMutation(c config, op Op, opts ...eatinghistoryOption) *EatinghistoryMutation {
	m := &EatinghistoryMutation{
		config:        c,
		op:            op,
		typ:           TypeEatinghistory,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEatinghistoryID sets the id field of the mutation.
func withEatinghistoryID(id int) eatinghistoryOption {
	return func(m *EatinghistoryMutation) {
		var (
			err   error
			once  sync.Once
			value *Eatinghistory
		)
		m.oldValue = func(ctx context.Context) (*Eatinghistory, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Eatinghistory.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEatinghistory sets the old Eatinghistory of the mutation.
func withEatinghistory(node *Eatinghistory) eatinghistoryOption {
	return func(m *EatinghistoryMutation) {
		m.oldValue = func(context.Context) (*Eatinghistory, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EatinghistoryMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EatinghistoryMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *EatinghistoryMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetAddedTime sets the added_time field.
func (m *EatinghistoryMutation) SetAddedTime(t time.Time) {
	m.added_time = &t
}

// AddedTime returns the added_time value in the mutation.
func (m *EatinghistoryMutation) AddedTime() (r time.Time, exists bool) {
	v := m.added_time
	if v == nil {
		return
	}
	return *v, true
}

// OldAddedTime returns the old added_time value of the Eatinghistory.
// If the Eatinghistory object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *EatinghistoryMutation) OldAddedTime(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldAddedTime is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldAddedTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddedTime: %w", err)
	}
	return oldValue.AddedTime, nil
}

// ResetAddedTime reset all changes of the "added_time" field.
func (m *EatinghistoryMutation) ResetAddedTime() {
	m.added_time = nil
}

// SetFoodmenuID sets the foodmenu edge to Foodmenu by id.
func (m *EatinghistoryMutation) SetFoodmenuID(id int) {
	m.foodmenu = &id
}

// ClearFoodmenu clears the foodmenu edge to Foodmenu.
func (m *EatinghistoryMutation) ClearFoodmenu() {
	m.clearedfoodmenu = true
}

// FoodmenuCleared returns if the edge foodmenu was cleared.
func (m *EatinghistoryMutation) FoodmenuCleared() bool {
	return m.clearedfoodmenu
}

// FoodmenuID returns the foodmenu id in the mutation.
func (m *EatinghistoryMutation) FoodmenuID() (id int, exists bool) {
	if m.foodmenu != nil {
		return *m.foodmenu, true
	}
	return
}

// FoodmenuIDs returns the foodmenu ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// FoodmenuID instead. It exists only for internal usage by the builders.
func (m *EatinghistoryMutation) FoodmenuIDs() (ids []int) {
	if id := m.foodmenu; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetFoodmenu reset all changes of the "foodmenu" edge.
func (m *EatinghistoryMutation) ResetFoodmenu() {
	m.foodmenu = nil
	m.clearedfoodmenu = false
}

// SetMealplanID sets the mealplan edge to Mealplan by id.
func (m *EatinghistoryMutation) SetMealplanID(id int) {
	m.mealplan = &id
}

// ClearMealplan clears the mealplan edge to Mealplan.
func (m *EatinghistoryMutation) ClearMealplan() {
	m.clearedmealplan = true
}

// MealplanCleared returns if the edge mealplan was cleared.
func (m *EatinghistoryMutation) MealplanCleared() bool {
	return m.clearedmealplan
}

// MealplanID returns the mealplan id in the mutation.
func (m *EatinghistoryMutation) MealplanID() (id int, exists bool) {
	if m.mealplan != nil {
		return *m.mealplan, true
	}
	return
}

// MealplanIDs returns the mealplan ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// MealplanID instead. It exists only for internal usage by the builders.
func (m *EatinghistoryMutation) MealplanIDs() (ids []int) {
	if id := m.mealplan; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetMealplan reset all changes of the "mealplan" edge.
func (m *EatinghistoryMutation) ResetMealplan() {
	m.mealplan = nil
	m.clearedmealplan = false
}

// SetTasteID sets the taste edge to Taste by id.
func (m *EatinghistoryMutation) SetTasteID(id int) {
	m.taste = &id
}

// ClearTaste clears the taste edge to Taste.
func (m *EatinghistoryMutation) ClearTaste() {
	m.clearedtaste = true
}

// TasteCleared returns if the edge taste was cleared.
func (m *EatinghistoryMutation) TasteCleared() bool {
	return m.clearedtaste
}

// TasteID returns the taste id in the mutation.
func (m *EatinghistoryMutation) TasteID() (id int, exists bool) {
	if m.taste != nil {
		return *m.taste, true
	}
	return
}

// TasteIDs returns the taste ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// TasteID instead. It exists only for internal usage by the builders.
func (m *EatinghistoryMutation) TasteIDs() (ids []int) {
	if id := m.taste; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTaste reset all changes of the "taste" edge.
func (m *EatinghistoryMutation) ResetTaste() {
	m.taste = nil
	m.clearedtaste = false
}

// SetUserID sets the user edge to User by id.
func (m *EatinghistoryMutation) SetUserID(id int) {
	m.user = &id
}

// ClearUser clears the user edge to User.
func (m *EatinghistoryMutation) ClearUser() {
	m.cleareduser = true
}

// UserCleared returns if the edge user was cleared.
func (m *EatinghistoryMutation) UserCleared() bool {
	return m.cleareduser
}

// UserID returns the user id in the mutation.
func (m *EatinghistoryMutation) UserID() (id int, exists bool) {
	if m.user != nil {
		return *m.user, true
	}
	return
}

// UserIDs returns the user ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// UserID instead. It exists only for internal usage by the builders.
func (m *EatinghistoryMutation) UserIDs() (ids []int) {
	if id := m.user; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetUser reset all changes of the "user" edge.
func (m *EatinghistoryMutation) ResetUser() {
	m.user = nil
	m.cleareduser = false
}

// Op returns the operation name.
func (m *EatinghistoryMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Eatinghistory).
func (m *EatinghistoryMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *EatinghistoryMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.added_time != nil {
		fields = append(fields, eatinghistory.FieldAddedTime)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *EatinghistoryMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case eatinghistory.FieldAddedTime:
		return m.AddedTime()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *EatinghistoryMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case eatinghistory.FieldAddedTime:
		return m.OldAddedTime(ctx)
	}
	return nil, fmt.Errorf("unknown Eatinghistory field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *EatinghistoryMutation) SetField(name string, value ent.Value) error {
	switch name {
	case eatinghistory.FieldAddedTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddedTime(v)
		return nil
	}
	return fmt.Errorf("unknown Eatinghistory field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *EatinghistoryMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *EatinghistoryMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *EatinghistoryMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Eatinghistory numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *EatinghistoryMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *EatinghistoryMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *EatinghistoryMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Eatinghistory nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *EatinghistoryMutation) ResetField(name string) error {
	switch name {
	case eatinghistory.FieldAddedTime:
		m.ResetAddedTime()
		return nil
	}
	return fmt.Errorf("unknown Eatinghistory field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *EatinghistoryMutation) AddedEdges() []string {
	edges := make([]string, 0, 4)
	if m.foodmenu != nil {
		edges = append(edges, eatinghistory.EdgeFoodmenu)
	}
	if m.mealplan != nil {
		edges = append(edges, eatinghistory.EdgeMealplan)
	}
	if m.taste != nil {
		edges = append(edges, eatinghistory.EdgeTaste)
	}
	if m.user != nil {
		edges = append(edges, eatinghistory.EdgeUser)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *EatinghistoryMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case eatinghistory.EdgeFoodmenu:
		if id := m.foodmenu; id != nil {
			return []ent.Value{*id}
		}
	case eatinghistory.EdgeMealplan:
		if id := m.mealplan; id != nil {
			return []ent.Value{*id}
		}
	case eatinghistory.EdgeTaste:
		if id := m.taste; id != nil {
			return []ent.Value{*id}
		}
	case eatinghistory.EdgeUser:
		if id := m.user; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *EatinghistoryMutation) RemovedEdges() []string {
	edges := make([]string, 0, 4)
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *EatinghistoryMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *EatinghistoryMutation) ClearedEdges() []string {
	edges := make([]string, 0, 4)
	if m.clearedfoodmenu {
		edges = append(edges, eatinghistory.EdgeFoodmenu)
	}
	if m.clearedmealplan {
		edges = append(edges, eatinghistory.EdgeMealplan)
	}
	if m.clearedtaste {
		edges = append(edges, eatinghistory.EdgeTaste)
	}
	if m.cleareduser {
		edges = append(edges, eatinghistory.EdgeUser)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *EatinghistoryMutation) EdgeCleared(name string) bool {
	switch name {
	case eatinghistory.EdgeFoodmenu:
		return m.clearedfoodmenu
	case eatinghistory.EdgeMealplan:
		return m.clearedmealplan
	case eatinghistory.EdgeTaste:
		return m.clearedtaste
	case eatinghistory.EdgeUser:
		return m.cleareduser
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *EatinghistoryMutation) ClearEdge(name string) error {
	switch name {
	case eatinghistory.EdgeFoodmenu:
		m.ClearFoodmenu()
		return nil
	case eatinghistory.EdgeMealplan:
		m.ClearMealplan()
		return nil
	case eatinghistory.EdgeTaste:
		m.ClearTaste()
		return nil
	case eatinghistory.EdgeUser:
		m.ClearUser()
		return nil
	}
	return fmt.Errorf("unknown Eatinghistory unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *EatinghistoryMutation) ResetEdge(name string) error {
	switch name {
	case eatinghistory.EdgeFoodmenu:
		m.ResetFoodmenu()
		return nil
	case eatinghistory.EdgeMealplan:
		m.ResetMealplan()
		return nil
	case eatinghistory.EdgeTaste:
		m.ResetTaste()
		return nil
	case eatinghistory.EdgeUser:
		m.ResetUser()
		return nil
	}
	return fmt.Errorf("unknown Eatinghistory edge %s", name)
}

// FoodmenuMutation represents an operation that mutate the Foodmenus
// nodes in the graph.
type FoodmenuMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	foodmenu_name        *string
	foodmenu_type        *string
	clearedFields        map[string]struct{}
	owner                *int
	clearedowner         bool
	eatinghistory        map[int]struct{}
	removedeatinghistory map[int]struct{}
	done                 bool
	oldValue             func(context.Context) (*Foodmenu, error)
}

var _ ent.Mutation = (*FoodmenuMutation)(nil)

// foodmenuOption allows to manage the mutation configuration using functional options.
type foodmenuOption func(*FoodmenuMutation)

// newFoodmenuMutation creates new mutation for $n.Name.
func newFoodmenuMutation(c config, op Op, opts ...foodmenuOption) *FoodmenuMutation {
	m := &FoodmenuMutation{
		config:        c,
		op:            op,
		typ:           TypeFoodmenu,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFoodmenuID sets the id field of the mutation.
func withFoodmenuID(id int) foodmenuOption {
	return func(m *FoodmenuMutation) {
		var (
			err   error
			once  sync.Once
			value *Foodmenu
		)
		m.oldValue = func(ctx context.Context) (*Foodmenu, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Foodmenu.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFoodmenu sets the old Foodmenu of the mutation.
func withFoodmenu(node *Foodmenu) foodmenuOption {
	return func(m *FoodmenuMutation) {
		m.oldValue = func(context.Context) (*Foodmenu, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FoodmenuMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FoodmenuMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *FoodmenuMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetFoodmenuName sets the foodmenu_name field.
func (m *FoodmenuMutation) SetFoodmenuName(s string) {
	m.foodmenu_name = &s
}

// FoodmenuName returns the foodmenu_name value in the mutation.
func (m *FoodmenuMutation) FoodmenuName() (r string, exists bool) {
	v := m.foodmenu_name
	if v == nil {
		return
	}
	return *v, true
}

// OldFoodmenuName returns the old foodmenu_name value of the Foodmenu.
// If the Foodmenu object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *FoodmenuMutation) OldFoodmenuName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldFoodmenuName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldFoodmenuName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFoodmenuName: %w", err)
	}
	return oldValue.FoodmenuName, nil
}

// ResetFoodmenuName reset all changes of the "foodmenu_name" field.
func (m *FoodmenuMutation) ResetFoodmenuName() {
	m.foodmenu_name = nil
}

// SetFoodmenuType sets the foodmenu_type field.
func (m *FoodmenuMutation) SetFoodmenuType(s string) {
	m.foodmenu_type = &s
}

// FoodmenuType returns the foodmenu_type value in the mutation.
func (m *FoodmenuMutation) FoodmenuType() (r string, exists bool) {
	v := m.foodmenu_type
	if v == nil {
		return
	}
	return *v, true
}

// OldFoodmenuType returns the old foodmenu_type value of the Foodmenu.
// If the Foodmenu object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *FoodmenuMutation) OldFoodmenuType(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldFoodmenuType is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldFoodmenuType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldFoodmenuType: %w", err)
	}
	return oldValue.FoodmenuType, nil
}

// ResetFoodmenuType reset all changes of the "foodmenu_type" field.
func (m *FoodmenuMutation) ResetFoodmenuType() {
	m.foodmenu_type = nil
}

// SetOwnerID sets the owner edge to User by id.
func (m *FoodmenuMutation) SetOwnerID(id int) {
	m.owner = &id
}

// ClearOwner clears the owner edge to User.
func (m *FoodmenuMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared returns if the edge owner was cleared.
func (m *FoodmenuMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the owner id in the mutation.
func (m *FoodmenuMutation) OwnerID() (id int, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the owner ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *FoodmenuMutation) OwnerIDs() (ids []int) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner reset all changes of the "owner" edge.
func (m *FoodmenuMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// AddEatinghistoryIDs adds the eatinghistory edge to Eatinghistory by ids.
func (m *FoodmenuMutation) AddEatinghistoryIDs(ids ...int) {
	if m.eatinghistory == nil {
		m.eatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.eatinghistory[ids[i]] = struct{}{}
	}
}

// RemoveEatinghistoryIDs removes the eatinghistory edge to Eatinghistory by ids.
func (m *FoodmenuMutation) RemoveEatinghistoryIDs(ids ...int) {
	if m.removedeatinghistory == nil {
		m.removedeatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.removedeatinghistory[ids[i]] = struct{}{}
	}
}

// RemovedEatinghistory returns the removed ids of eatinghistory.
func (m *FoodmenuMutation) RemovedEatinghistoryIDs() (ids []int) {
	for id := range m.removedeatinghistory {
		ids = append(ids, id)
	}
	return
}

// EatinghistoryIDs returns the eatinghistory ids in the mutation.
func (m *FoodmenuMutation) EatinghistoryIDs() (ids []int) {
	for id := range m.eatinghistory {
		ids = append(ids, id)
	}
	return
}

// ResetEatinghistory reset all changes of the "eatinghistory" edge.
func (m *FoodmenuMutation) ResetEatinghistory() {
	m.eatinghistory = nil
	m.removedeatinghistory = nil
}

// Op returns the operation name.
func (m *FoodmenuMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Foodmenu).
func (m *FoodmenuMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *FoodmenuMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.foodmenu_name != nil {
		fields = append(fields, foodmenu.FieldFoodmenuName)
	}
	if m.foodmenu_type != nil {
		fields = append(fields, foodmenu.FieldFoodmenuType)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *FoodmenuMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case foodmenu.FieldFoodmenuName:
		return m.FoodmenuName()
	case foodmenu.FieldFoodmenuType:
		return m.FoodmenuType()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *FoodmenuMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case foodmenu.FieldFoodmenuName:
		return m.OldFoodmenuName(ctx)
	case foodmenu.FieldFoodmenuType:
		return m.OldFoodmenuType(ctx)
	}
	return nil, fmt.Errorf("unknown Foodmenu field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *FoodmenuMutation) SetField(name string, value ent.Value) error {
	switch name {
	case foodmenu.FieldFoodmenuName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFoodmenuName(v)
		return nil
	case foodmenu.FieldFoodmenuType:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetFoodmenuType(v)
		return nil
	}
	return fmt.Errorf("unknown Foodmenu field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *FoodmenuMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *FoodmenuMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *FoodmenuMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Foodmenu numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *FoodmenuMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *FoodmenuMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *FoodmenuMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Foodmenu nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *FoodmenuMutation) ResetField(name string) error {
	switch name {
	case foodmenu.FieldFoodmenuName:
		m.ResetFoodmenuName()
		return nil
	case foodmenu.FieldFoodmenuType:
		m.ResetFoodmenuType()
		return nil
	}
	return fmt.Errorf("unknown Foodmenu field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *FoodmenuMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, foodmenu.EdgeOwner)
	}
	if m.eatinghistory != nil {
		edges = append(edges, foodmenu.EdgeEatinghistory)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *FoodmenuMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case foodmenu.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	case foodmenu.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.eatinghistory))
		for id := range m.eatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *FoodmenuMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedeatinghistory != nil {
		edges = append(edges, foodmenu.EdgeEatinghistory)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *FoodmenuMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case foodmenu.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.removedeatinghistory))
		for id := range m.removedeatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *FoodmenuMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, foodmenu.EdgeOwner)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *FoodmenuMutation) EdgeCleared(name string) bool {
	switch name {
	case foodmenu.EdgeOwner:
		return m.clearedowner
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *FoodmenuMutation) ClearEdge(name string) error {
	switch name {
	case foodmenu.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Foodmenu unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *FoodmenuMutation) ResetEdge(name string) error {
	switch name {
	case foodmenu.EdgeOwner:
		m.ResetOwner()
		return nil
	case foodmenu.EdgeEatinghistory:
		m.ResetEatinghistory()
		return nil
	}
	return fmt.Errorf("unknown Foodmenu edge %s", name)
}

// MealplanMutation represents an operation that mutate the Mealplans
// nodes in the graph.
type MealplanMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	mealplan_name        *string
	clearedFields        map[string]struct{}
	owner                *int
	clearedowner         bool
	eatinghistory        map[int]struct{}
	removedeatinghistory map[int]struct{}
	done                 bool
	oldValue             func(context.Context) (*Mealplan, error)
}

var _ ent.Mutation = (*MealplanMutation)(nil)

// mealplanOption allows to manage the mutation configuration using functional options.
type mealplanOption func(*MealplanMutation)

// newMealplanMutation creates new mutation for $n.Name.
func newMealplanMutation(c config, op Op, opts ...mealplanOption) *MealplanMutation {
	m := &MealplanMutation{
		config:        c,
		op:            op,
		typ:           TypeMealplan,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withMealplanID sets the id field of the mutation.
func withMealplanID(id int) mealplanOption {
	return func(m *MealplanMutation) {
		var (
			err   error
			once  sync.Once
			value *Mealplan
		)
		m.oldValue = func(ctx context.Context) (*Mealplan, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Mealplan.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withMealplan sets the old Mealplan of the mutation.
func withMealplan(node *Mealplan) mealplanOption {
	return func(m *MealplanMutation) {
		m.oldValue = func(context.Context) (*Mealplan, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m MealplanMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m MealplanMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *MealplanMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetMealplanName sets the mealplan_name field.
func (m *MealplanMutation) SetMealplanName(s string) {
	m.mealplan_name = &s
}

// MealplanName returns the mealplan_name value in the mutation.
func (m *MealplanMutation) MealplanName() (r string, exists bool) {
	v := m.mealplan_name
	if v == nil {
		return
	}
	return *v, true
}

// OldMealplanName returns the old mealplan_name value of the Mealplan.
// If the Mealplan object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *MealplanMutation) OldMealplanName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldMealplanName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldMealplanName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMealplanName: %w", err)
	}
	return oldValue.MealplanName, nil
}

// ResetMealplanName reset all changes of the "mealplan_name" field.
func (m *MealplanMutation) ResetMealplanName() {
	m.mealplan_name = nil
}

// SetOwnerID sets the owner edge to User by id.
func (m *MealplanMutation) SetOwnerID(id int) {
	m.owner = &id
}

// ClearOwner clears the owner edge to User.
func (m *MealplanMutation) ClearOwner() {
	m.clearedowner = true
}

// OwnerCleared returns if the edge owner was cleared.
func (m *MealplanMutation) OwnerCleared() bool {
	return m.clearedowner
}

// OwnerID returns the owner id in the mutation.
func (m *MealplanMutation) OwnerID() (id int, exists bool) {
	if m.owner != nil {
		return *m.owner, true
	}
	return
}

// OwnerIDs returns the owner ids in the mutation.
// Note that ids always returns len(ids) <= 1 for unique edges, and you should use
// OwnerID instead. It exists only for internal usage by the builders.
func (m *MealplanMutation) OwnerIDs() (ids []int) {
	if id := m.owner; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetOwner reset all changes of the "owner" edge.
func (m *MealplanMutation) ResetOwner() {
	m.owner = nil
	m.clearedowner = false
}

// AddEatinghistoryIDs adds the eatinghistory edge to Eatinghistory by ids.
func (m *MealplanMutation) AddEatinghistoryIDs(ids ...int) {
	if m.eatinghistory == nil {
		m.eatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.eatinghistory[ids[i]] = struct{}{}
	}
}

// RemoveEatinghistoryIDs removes the eatinghistory edge to Eatinghistory by ids.
func (m *MealplanMutation) RemoveEatinghistoryIDs(ids ...int) {
	if m.removedeatinghistory == nil {
		m.removedeatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.removedeatinghistory[ids[i]] = struct{}{}
	}
}

// RemovedEatinghistory returns the removed ids of eatinghistory.
func (m *MealplanMutation) RemovedEatinghistoryIDs() (ids []int) {
	for id := range m.removedeatinghistory {
		ids = append(ids, id)
	}
	return
}

// EatinghistoryIDs returns the eatinghistory ids in the mutation.
func (m *MealplanMutation) EatinghistoryIDs() (ids []int) {
	for id := range m.eatinghistory {
		ids = append(ids, id)
	}
	return
}

// ResetEatinghistory reset all changes of the "eatinghistory" edge.
func (m *MealplanMutation) ResetEatinghistory() {
	m.eatinghistory = nil
	m.removedeatinghistory = nil
}

// Op returns the operation name.
func (m *MealplanMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Mealplan).
func (m *MealplanMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *MealplanMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.mealplan_name != nil {
		fields = append(fields, mealplan.FieldMealplanName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *MealplanMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case mealplan.FieldMealplanName:
		return m.MealplanName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *MealplanMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case mealplan.FieldMealplanName:
		return m.OldMealplanName(ctx)
	}
	return nil, fmt.Errorf("unknown Mealplan field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *MealplanMutation) SetField(name string, value ent.Value) error {
	switch name {
	case mealplan.FieldMealplanName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMealplanName(v)
		return nil
	}
	return fmt.Errorf("unknown Mealplan field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *MealplanMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *MealplanMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *MealplanMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Mealplan numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *MealplanMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *MealplanMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *MealplanMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Mealplan nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *MealplanMutation) ResetField(name string) error {
	switch name {
	case mealplan.FieldMealplanName:
		m.ResetMealplanName()
		return nil
	}
	return fmt.Errorf("unknown Mealplan field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *MealplanMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.owner != nil {
		edges = append(edges, mealplan.EdgeOwner)
	}
	if m.eatinghistory != nil {
		edges = append(edges, mealplan.EdgeEatinghistory)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *MealplanMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case mealplan.EdgeOwner:
		if id := m.owner; id != nil {
			return []ent.Value{*id}
		}
	case mealplan.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.eatinghistory))
		for id := range m.eatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *MealplanMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedeatinghistory != nil {
		edges = append(edges, mealplan.EdgeEatinghistory)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *MealplanMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case mealplan.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.removedeatinghistory))
		for id := range m.removedeatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *MealplanMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedowner {
		edges = append(edges, mealplan.EdgeOwner)
	}
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *MealplanMutation) EdgeCleared(name string) bool {
	switch name {
	case mealplan.EdgeOwner:
		return m.clearedowner
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *MealplanMutation) ClearEdge(name string) error {
	switch name {
	case mealplan.EdgeOwner:
		m.ClearOwner()
		return nil
	}
	return fmt.Errorf("unknown Mealplan unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *MealplanMutation) ResetEdge(name string) error {
	switch name {
	case mealplan.EdgeOwner:
		m.ResetOwner()
		return nil
	case mealplan.EdgeEatinghistory:
		m.ResetEatinghistory()
		return nil
	}
	return fmt.Errorf("unknown Mealplan edge %s", name)
}

// TasteMutation represents an operation that mutate the Tastes
// nodes in the graph.
type TasteMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	taste_name           *string
	clearedFields        map[string]struct{}
	eatinghistory        map[int]struct{}
	removedeatinghistory map[int]struct{}
	done                 bool
	oldValue             func(context.Context) (*Taste, error)
}

var _ ent.Mutation = (*TasteMutation)(nil)

// tasteOption allows to manage the mutation configuration using functional options.
type tasteOption func(*TasteMutation)

// newTasteMutation creates new mutation for $n.Name.
func newTasteMutation(c config, op Op, opts ...tasteOption) *TasteMutation {
	m := &TasteMutation{
		config:        c,
		op:            op,
		typ:           TypeTaste,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTasteID sets the id field of the mutation.
func withTasteID(id int) tasteOption {
	return func(m *TasteMutation) {
		var (
			err   error
			once  sync.Once
			value *Taste
		)
		m.oldValue = func(ctx context.Context) (*Taste, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Taste.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTaste sets the old Taste of the mutation.
func withTaste(node *Taste) tasteOption {
	return func(m *TasteMutation) {
		m.oldValue = func(context.Context) (*Taste, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TasteMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TasteMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *TasteMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetTasteName sets the taste_name field.
func (m *TasteMutation) SetTasteName(s string) {
	m.taste_name = &s
}

// TasteName returns the taste_name value in the mutation.
func (m *TasteMutation) TasteName() (r string, exists bool) {
	v := m.taste_name
	if v == nil {
		return
	}
	return *v, true
}

// OldTasteName returns the old taste_name value of the Taste.
// If the Taste object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *TasteMutation) OldTasteName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldTasteName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldTasteName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTasteName: %w", err)
	}
	return oldValue.TasteName, nil
}

// ResetTasteName reset all changes of the "taste_name" field.
func (m *TasteMutation) ResetTasteName() {
	m.taste_name = nil
}

// AddEatinghistoryIDs adds the eatinghistory edge to Eatinghistory by ids.
func (m *TasteMutation) AddEatinghistoryIDs(ids ...int) {
	if m.eatinghistory == nil {
		m.eatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.eatinghistory[ids[i]] = struct{}{}
	}
}

// RemoveEatinghistoryIDs removes the eatinghistory edge to Eatinghistory by ids.
func (m *TasteMutation) RemoveEatinghistoryIDs(ids ...int) {
	if m.removedeatinghistory == nil {
		m.removedeatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.removedeatinghistory[ids[i]] = struct{}{}
	}
}

// RemovedEatinghistory returns the removed ids of eatinghistory.
func (m *TasteMutation) RemovedEatinghistoryIDs() (ids []int) {
	for id := range m.removedeatinghistory {
		ids = append(ids, id)
	}
	return
}

// EatinghistoryIDs returns the eatinghistory ids in the mutation.
func (m *TasteMutation) EatinghistoryIDs() (ids []int) {
	for id := range m.eatinghistory {
		ids = append(ids, id)
	}
	return
}

// ResetEatinghistory reset all changes of the "eatinghistory" edge.
func (m *TasteMutation) ResetEatinghistory() {
	m.eatinghistory = nil
	m.removedeatinghistory = nil
}

// Op returns the operation name.
func (m *TasteMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Taste).
func (m *TasteMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *TasteMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.taste_name != nil {
		fields = append(fields, taste.FieldTasteName)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *TasteMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case taste.FieldTasteName:
		return m.TasteName()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *TasteMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case taste.FieldTasteName:
		return m.OldTasteName(ctx)
	}
	return nil, fmt.Errorf("unknown Taste field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *TasteMutation) SetField(name string, value ent.Value) error {
	switch name {
	case taste.FieldTasteName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTasteName(v)
		return nil
	}
	return fmt.Errorf("unknown Taste field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *TasteMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *TasteMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *TasteMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Taste numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *TasteMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *TasteMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *TasteMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Taste nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *TasteMutation) ResetField(name string) error {
	switch name {
	case taste.FieldTasteName:
		m.ResetTasteName()
		return nil
	}
	return fmt.Errorf("unknown Taste field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *TasteMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.eatinghistory != nil {
		edges = append(edges, taste.EdgeEatinghistory)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *TasteMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case taste.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.eatinghistory))
		for id := range m.eatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *TasteMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedeatinghistory != nil {
		edges = append(edges, taste.EdgeEatinghistory)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *TasteMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case taste.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.removedeatinghistory))
		for id := range m.removedeatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *TasteMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *TasteMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *TasteMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Taste unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *TasteMutation) ResetEdge(name string) error {
	switch name {
	case taste.EdgeEatinghistory:
		m.ResetEatinghistory()
		return nil
	}
	return fmt.Errorf("unknown Taste edge %s", name)
}

// UserMutation represents an operation that mutate the Users
// nodes in the graph.
type UserMutation struct {
	config
	op                   Op
	typ                  string
	id                   *int
	name                 *string
	email                *string
	clearedFields        map[string]struct{}
	mealplan             map[int]struct{}
	removedmealplan      map[int]struct{}
	foodmenu             map[int]struct{}
	removedfoodmenu      map[int]struct{}
	eatinghistory        map[int]struct{}
	removedeatinghistory map[int]struct{}
	done                 bool
	oldValue             func(context.Context) (*User, error)
}

var _ ent.Mutation = (*UserMutation)(nil)

// userOption allows to manage the mutation configuration using functional options.
type userOption func(*UserMutation)

// newUserMutation creates new mutation for $n.Name.
func newUserMutation(c config, op Op, opts ...userOption) *UserMutation {
	m := &UserMutation{
		config:        c,
		op:            op,
		typ:           TypeUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withUserID sets the id field of the mutation.
func withUserID(id int) userOption {
	return func(m *UserMutation) {
		var (
			err   error
			once  sync.Once
			value *User
		)
		m.oldValue = func(ctx context.Context) (*User, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().User.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withUser sets the old User of the mutation.
func withUser(node *User) userOption {
	return func(m *UserMutation) {
		m.oldValue = func(context.Context) (*User, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m UserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m UserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the id value in the mutation. Note that, the id
// is available only if it was provided to the builder.
func (m *UserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the name field.
func (m *UserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the name value in the mutation.
func (m *UserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old name value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName reset all changes of the "name" field.
func (m *UserMutation) ResetName() {
	m.name = nil
}

// SetEmail sets the email field.
func (m *UserMutation) SetEmail(s string) {
	m.email = &s
}

// Email returns the email value in the mutation.
func (m *UserMutation) Email() (r string, exists bool) {
	v := m.email
	if v == nil {
		return
	}
	return *v, true
}

// OldEmail returns the old email value of the User.
// If the User object wasn't provided to the builder, the object is fetched
// from the database.
// An error is returned if the mutation operation is not UpdateOne, or database query fails.
func (m *UserMutation) OldEmail(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldEmail is allowed only on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldEmail requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmail: %w", err)
	}
	return oldValue.Email, nil
}

// ResetEmail reset all changes of the "email" field.
func (m *UserMutation) ResetEmail() {
	m.email = nil
}

// AddMealplanIDs adds the mealplan edge to Mealplan by ids.
func (m *UserMutation) AddMealplanIDs(ids ...int) {
	if m.mealplan == nil {
		m.mealplan = make(map[int]struct{})
	}
	for i := range ids {
		m.mealplan[ids[i]] = struct{}{}
	}
}

// RemoveMealplanIDs removes the mealplan edge to Mealplan by ids.
func (m *UserMutation) RemoveMealplanIDs(ids ...int) {
	if m.removedmealplan == nil {
		m.removedmealplan = make(map[int]struct{})
	}
	for i := range ids {
		m.removedmealplan[ids[i]] = struct{}{}
	}
}

// RemovedMealplan returns the removed ids of mealplan.
func (m *UserMutation) RemovedMealplanIDs() (ids []int) {
	for id := range m.removedmealplan {
		ids = append(ids, id)
	}
	return
}

// MealplanIDs returns the mealplan ids in the mutation.
func (m *UserMutation) MealplanIDs() (ids []int) {
	for id := range m.mealplan {
		ids = append(ids, id)
	}
	return
}

// ResetMealplan reset all changes of the "mealplan" edge.
func (m *UserMutation) ResetMealplan() {
	m.mealplan = nil
	m.removedmealplan = nil
}

// AddFoodmenuIDs adds the foodmenu edge to Foodmenu by ids.
func (m *UserMutation) AddFoodmenuIDs(ids ...int) {
	if m.foodmenu == nil {
		m.foodmenu = make(map[int]struct{})
	}
	for i := range ids {
		m.foodmenu[ids[i]] = struct{}{}
	}
}

// RemoveFoodmenuIDs removes the foodmenu edge to Foodmenu by ids.
func (m *UserMutation) RemoveFoodmenuIDs(ids ...int) {
	if m.removedfoodmenu == nil {
		m.removedfoodmenu = make(map[int]struct{})
	}
	for i := range ids {
		m.removedfoodmenu[ids[i]] = struct{}{}
	}
}

// RemovedFoodmenu returns the removed ids of foodmenu.
func (m *UserMutation) RemovedFoodmenuIDs() (ids []int) {
	for id := range m.removedfoodmenu {
		ids = append(ids, id)
	}
	return
}

// FoodmenuIDs returns the foodmenu ids in the mutation.
func (m *UserMutation) FoodmenuIDs() (ids []int) {
	for id := range m.foodmenu {
		ids = append(ids, id)
	}
	return
}

// ResetFoodmenu reset all changes of the "foodmenu" edge.
func (m *UserMutation) ResetFoodmenu() {
	m.foodmenu = nil
	m.removedfoodmenu = nil
}

// AddEatinghistoryIDs adds the eatinghistory edge to Eatinghistory by ids.
func (m *UserMutation) AddEatinghistoryIDs(ids ...int) {
	if m.eatinghistory == nil {
		m.eatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.eatinghistory[ids[i]] = struct{}{}
	}
}

// RemoveEatinghistoryIDs removes the eatinghistory edge to Eatinghistory by ids.
func (m *UserMutation) RemoveEatinghistoryIDs(ids ...int) {
	if m.removedeatinghistory == nil {
		m.removedeatinghistory = make(map[int]struct{})
	}
	for i := range ids {
		m.removedeatinghistory[ids[i]] = struct{}{}
	}
}

// RemovedEatinghistory returns the removed ids of eatinghistory.
func (m *UserMutation) RemovedEatinghistoryIDs() (ids []int) {
	for id := range m.removedeatinghistory {
		ids = append(ids, id)
	}
	return
}

// EatinghistoryIDs returns the eatinghistory ids in the mutation.
func (m *UserMutation) EatinghistoryIDs() (ids []int) {
	for id := range m.eatinghistory {
		ids = append(ids, id)
	}
	return
}

// ResetEatinghistory reset all changes of the "eatinghistory" edge.
func (m *UserMutation) ResetEatinghistory() {
	m.eatinghistory = nil
	m.removedeatinghistory = nil
}

// Op returns the operation name.
func (m *UserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (User).
func (m *UserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during
// this mutation. Note that, in order to get all numeric
// fields that were in/decremented, call AddedFields().
func (m *UserMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, user.FieldName)
	}
	if m.email != nil {
		fields = append(fields, user.FieldEmail)
	}
	return fields
}

// Field returns the value of a field with the given name.
// The second boolean value indicates that this field was
// not set, or was not define in the schema.
func (m *UserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case user.FieldName:
		return m.Name()
	case user.FieldEmail:
		return m.Email()
	}
	return nil, false
}

// OldField returns the old value of the field from the database.
// An error is returned if the mutation operation is not UpdateOne,
// or the query to the database was failed.
func (m *UserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case user.FieldName:
		return m.OldName(ctx)
	case user.FieldEmail:
		return m.OldEmail(ctx)
	}
	return nil, fmt.Errorf("unknown User field %s", name)
}

// SetField sets the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case user.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case user.FieldEmail:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmail(v)
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedFields returns all numeric fields that were incremented
// or decremented during this mutation.
func (m *UserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was in/decremented
// from a field with the given name. The second value indicates
// that this field was not set, or was not define in the schema.
func (m *UserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value for the given name. It returns an
// error if the field is not defined in the schema, or if the
// type mismatch the field type.
func (m *UserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown User numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared
// during this mutation.
func (m *UserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicates if this field was
// cleared in this mutation.
func (m *UserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value for the given name. It returns an
// error if the field is not defined in the schema.
func (m *UserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown User nullable field %s", name)
}

// ResetField resets all changes in the mutation regarding the
// given field name. It returns an error if the field is not
// defined in the schema.
func (m *UserMutation) ResetField(name string) error {
	switch name {
	case user.FieldName:
		m.ResetName()
		return nil
	case user.FieldEmail:
		m.ResetEmail()
		return nil
	}
	return fmt.Errorf("unknown User field %s", name)
}

// AddedEdges returns all edge names that were set/added in this
// mutation.
func (m *UserMutation) AddedEdges() []string {
	edges := make([]string, 0, 3)
	if m.mealplan != nil {
		edges = append(edges, user.EdgeMealplan)
	}
	if m.foodmenu != nil {
		edges = append(edges, user.EdgeFoodmenu)
	}
	if m.eatinghistory != nil {
		edges = append(edges, user.EdgeEatinghistory)
	}
	return edges
}

// AddedIDs returns all ids (to other nodes) that were added for
// the given edge name.
func (m *UserMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeMealplan:
		ids := make([]ent.Value, 0, len(m.mealplan))
		for id := range m.mealplan {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeFoodmenu:
		ids := make([]ent.Value, 0, len(m.foodmenu))
		for id := range m.foodmenu {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.eatinghistory))
		for id := range m.eatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this
// mutation.
func (m *UserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 3)
	if m.removedmealplan != nil {
		edges = append(edges, user.EdgeMealplan)
	}
	if m.removedfoodmenu != nil {
		edges = append(edges, user.EdgeFoodmenu)
	}
	if m.removedeatinghistory != nil {
		edges = append(edges, user.EdgeEatinghistory)
	}
	return edges
}

// RemovedIDs returns all ids (to other nodes) that were removed for
// the given edge name.
func (m *UserMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case user.EdgeMealplan:
		ids := make([]ent.Value, 0, len(m.removedmealplan))
		for id := range m.removedmealplan {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeFoodmenu:
		ids := make([]ent.Value, 0, len(m.removedfoodmenu))
		for id := range m.removedfoodmenu {
			ids = append(ids, id)
		}
		return ids
	case user.EdgeEatinghistory:
		ids := make([]ent.Value, 0, len(m.removedeatinghistory))
		for id := range m.removedeatinghistory {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this
// mutation.
func (m *UserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 3)
	return edges
}

// EdgeCleared returns a boolean indicates if this edge was
// cleared in this mutation.
func (m *UserMutation) EdgeCleared(name string) bool {
	switch name {
	}
	return false
}

// ClearEdge clears the value for the given name. It returns an
// error if the edge name is not defined in the schema.
func (m *UserMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown User unique edge %s", name)
}

// ResetEdge resets all changes in the mutation regarding the
// given edge name. It returns an error if the edge is not
// defined in the schema.
func (m *UserMutation) ResetEdge(name string) error {
	switch name {
	case user.EdgeMealplan:
		m.ResetMealplan()
		return nil
	case user.EdgeFoodmenu:
		m.ResetFoodmenu()
		return nil
	case user.EdgeEatinghistory:
		m.ResetEatinghistory()
		return nil
	}
	return fmt.Errorf("unknown User edge %s", name)
}
