// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/Teeth/app/ent/eatinghistory"
	"github.com/Teeth/app/ent/taste"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// TasteCreate is the builder for creating a Taste entity.
type TasteCreate struct {
	config
	mutation *TasteMutation
	hooks    []Hook
}

// SetTasteName sets the taste_name field.
func (tc *TasteCreate) SetTasteName(s string) *TasteCreate {
	tc.mutation.SetTasteName(s)
	return tc
}

// AddEatinghistoryIDs adds the eatinghistory edge to Eatinghistory by ids.
func (tc *TasteCreate) AddEatinghistoryIDs(ids ...int) *TasteCreate {
	tc.mutation.AddEatinghistoryIDs(ids...)
	return tc
}

// AddEatinghistory adds the eatinghistory edges to Eatinghistory.
func (tc *TasteCreate) AddEatinghistory(e ...*Eatinghistory) *TasteCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return tc.AddEatinghistoryIDs(ids...)
}

// Mutation returns the TasteMutation object of the builder.
func (tc *TasteCreate) Mutation() *TasteMutation {
	return tc.mutation
}

// Save creates the Taste in the database.
func (tc *TasteCreate) Save(ctx context.Context) (*Taste, error) {
	if _, ok := tc.mutation.TasteName(); !ok {
		return nil, &ValidationError{Name: "taste_name", err: errors.New("ent: missing required field \"taste_name\"")}
	}
	if v, ok := tc.mutation.TasteName(); ok {
		if err := taste.TasteNameValidator(v); err != nil {
			return nil, &ValidationError{Name: "taste_name", err: fmt.Errorf("ent: validator failed for field \"taste_name\": %w", err)}
		}
	}
	var (
		err  error
		node *Taste
	)
	if len(tc.hooks) == 0 {
		node, err = tc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TasteMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			tc.mutation = mutation
			node, err = tc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(tc.hooks) - 1; i >= 0; i-- {
			mut = tc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tc *TasteCreate) SaveX(ctx context.Context) *Taste {
	v, err := tc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tc *TasteCreate) sqlSave(ctx context.Context) (*Taste, error) {
	t, _spec := tc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	t.ID = int(id)
	return t, nil
}

func (tc *TasteCreate) createSpec() (*Taste, *sqlgraph.CreateSpec) {
	var (
		t     = &Taste{config: tc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: taste.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: taste.FieldID,
			},
		}
	)
	if value, ok := tc.mutation.TasteName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: taste.FieldTasteName,
		})
		t.TasteName = value
	}
	if nodes := tc.mutation.EatinghistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   taste.EatinghistoryTable,
			Columns: []string{taste.EatinghistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: eatinghistory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return t, _spec
}
