// Code generated by entc, DO NOT EDIT.

package mealplan

const (
	// Label holds the string label denoting the mealplan type in the database.
	Label = "mealplan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMealplanName holds the string denoting the mealplan_name field in the database.
	FieldMealplanName = "mealplan_name"

	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeEatinghistory holds the string denoting the eatinghistory edge name in mutations.
	EdgeEatinghistory = "eatinghistory"

	// Table holds the table name of the mealplan in the database.
	Table = "mealplans"
	// OwnerTable is the table the holds the owner relation/edge.
	OwnerTable = "mealplans"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// EatinghistoryTable is the table the holds the eatinghistory relation/edge.
	EatinghistoryTable = "eatinghistories"
	// EatinghistoryInverseTable is the table name for the Eatinghistory entity.
	// It exists in this package in order to avoid circular dependency with the "eatinghistory" package.
	EatinghistoryInverseTable = "eatinghistories"
	// EatinghistoryColumn is the table column denoting the eatinghistory relation/edge.
	EatinghistoryColumn = "mealplan_id"
)

// Columns holds all SQL columns for mealplan fields.
var Columns = []string{
	FieldID,
	FieldMealplanName,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Mealplan type.
var ForeignKeys = []string{
	"owner_id",
}

var (
	// MealplanNameValidator is a validator for the "mealplan_name" field. It is called by the builders before save.
	MealplanNameValidator func(string) error
)
