// Code generated by entc, DO NOT EDIT.

package mealplan

import (
	"github.com/Teeth/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// MealplanName applies equality check predicate on the "mealplan_name" field. It's identical to MealplanNameEQ.
func MealplanName(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMealplanName), v))
	})
}

// MealplanNameEQ applies the EQ predicate on the "mealplan_name" field.
func MealplanNameEQ(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldMealplanName), v))
	})
}

// MealplanNameNEQ applies the NEQ predicate on the "mealplan_name" field.
func MealplanNameNEQ(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldMealplanName), v))
	})
}

// MealplanNameIn applies the In predicate on the "mealplan_name" field.
func MealplanNameIn(vs ...string) predicate.Mealplan {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Mealplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldMealplanName), v...))
	})
}

// MealplanNameNotIn applies the NotIn predicate on the "mealplan_name" field.
func MealplanNameNotIn(vs ...string) predicate.Mealplan {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Mealplan(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldMealplanName), v...))
	})
}

// MealplanNameGT applies the GT predicate on the "mealplan_name" field.
func MealplanNameGT(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldMealplanName), v))
	})
}

// MealplanNameGTE applies the GTE predicate on the "mealplan_name" field.
func MealplanNameGTE(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldMealplanName), v))
	})
}

// MealplanNameLT applies the LT predicate on the "mealplan_name" field.
func MealplanNameLT(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldMealplanName), v))
	})
}

// MealplanNameLTE applies the LTE predicate on the "mealplan_name" field.
func MealplanNameLTE(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldMealplanName), v))
	})
}

// MealplanNameContains applies the Contains predicate on the "mealplan_name" field.
func MealplanNameContains(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldMealplanName), v))
	})
}

// MealplanNameHasPrefix applies the HasPrefix predicate on the "mealplan_name" field.
func MealplanNameHasPrefix(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldMealplanName), v))
	})
}

// MealplanNameHasSuffix applies the HasSuffix predicate on the "mealplan_name" field.
func MealplanNameHasSuffix(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldMealplanName), v))
	})
}

// MealplanNameEqualFold applies the EqualFold predicate on the "mealplan_name" field.
func MealplanNameEqualFold(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldMealplanName), v))
	})
}

// MealplanNameContainsFold applies the ContainsFold predicate on the "mealplan_name" field.
func MealplanNameContainsFold(v string) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldMealplanName), v))
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(OwnerInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEatinghistory applies the HasEdge predicate on the "eatinghistory" edge.
func HasEatinghistory() predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EatinghistoryTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EatinghistoryTable, EatinghistoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEatinghistoryWith applies the HasEdge predicate on the "eatinghistory" edge with a given conditions (other predicates).
func HasEatinghistoryWith(preds ...predicate.Eatinghistory) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EatinghistoryInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EatinghistoryTable, EatinghistoryColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Mealplan) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Mealplan) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Mealplan) predicate.Mealplan {
	return predicate.Mealplan(func(s *sql.Selector) {
		p(s.Not())
	})
}
