// Code generated by entc, DO NOT EDIT.

package eatinghistory

const (
	// Label holds the string label denoting the eatinghistory type in the database.
	Label = "eatinghistory"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddedTime holds the string denoting the added_time field in the database.
	FieldAddedTime = "added_time"

	// EdgeFoodmenu holds the string denoting the foodmenu edge name in mutations.
	EdgeFoodmenu = "foodmenu"
	// EdgeMealplan holds the string denoting the mealplan edge name in mutations.
	EdgeMealplan = "mealplan"
	// EdgeTaste holds the string denoting the taste edge name in mutations.
	EdgeTaste = "taste"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"

	// Table holds the table name of the eatinghistory in the database.
	Table = "eatinghistories"
	// FoodmenuTable is the table the holds the foodmenu relation/edge.
	FoodmenuTable = "eatinghistories"
	// FoodmenuInverseTable is the table name for the Foodmenu entity.
	// It exists in this package in order to avoid circular dependency with the "foodmenu" package.
	FoodmenuInverseTable = "foodmenus"
	// FoodmenuColumn is the table column denoting the foodmenu relation/edge.
	FoodmenuColumn = "foodmenu_id"
	// MealplanTable is the table the holds the mealplan relation/edge.
	MealplanTable = "eatinghistories"
	// MealplanInverseTable is the table name for the Mealplan entity.
	// It exists in this package in order to avoid circular dependency with the "mealplan" package.
	MealplanInverseTable = "mealplans"
	// MealplanColumn is the table column denoting the mealplan relation/edge.
	MealplanColumn = "mealplan_id"
	// TasteTable is the table the holds the taste relation/edge.
	TasteTable = "eatinghistories"
	// TasteInverseTable is the table name for the Taste entity.
	// It exists in this package in order to avoid circular dependency with the "taste" package.
	TasteInverseTable = "tastes"
	// TasteColumn is the table column denoting the taste relation/edge.
	TasteColumn = "taste_id"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "eatinghistories"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for eatinghistory fields.
var Columns = []string{
	FieldID,
	FieldAddedTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Eatinghistory type.
var ForeignKeys = []string{
	"foodmenu_id",
	"mealplan_id",
	"taste_id",
	"user_id",
}
