/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersFoodmenu
 */
export interface ControllersFoodmenu {
    /**
     * 
     * @type {string}
     * @memberof ControllersFoodmenu
     */
    foodmenuname?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersFoodmenu
     */
    foodmenutype?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersFoodmenu
     */
    ownerid?: number;
}

export function ControllersFoodmenuFromJSON(json: any): ControllersFoodmenu {
    return ControllersFoodmenuFromJSONTyped(json, false);
}

export function ControllersFoodmenuFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersFoodmenu {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'foodmenuname': !exists(json, 'foodmenuname') ? undefined : json['foodmenuname'],
        'foodmenutype': !exists(json, 'foodmenutype') ? undefined : json['foodmenutype'],
        'ownerid': !exists(json, 'ownerid') ? undefined : json['ownerid'],
    };
}

export function ControllersFoodmenuToJSON(value?: ControllersFoodmenu | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'foodmenuname': value.foodmenuname,
        'foodmenutype': value.foodmenutype,
        'ownerid': value.ownerid,
    };
}


