/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersEatinghistory
 */
export interface ControllersEatinghistory {
    /**
     * 
     * @type {string}
     * @memberof ControllersEatinghistory
     */
    addedTime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersEatinghistory
     */
    foodmenuID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersEatinghistory
     */
    mealplanID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersEatinghistory
     */
    tasteID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersEatinghistory
     */
    userID?: number;
}

export function ControllersEatinghistoryFromJSON(json: any): ControllersEatinghistory {
    return ControllersEatinghistoryFromJSONTyped(json, false);
}

export function ControllersEatinghistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersEatinghistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addedTime': !exists(json, 'addedTime') ? undefined : json['addedTime'],
        'foodmenuID': !exists(json, 'foodmenuID') ? undefined : json['foodmenuID'],
        'mealplanID': !exists(json, 'mealplanID') ? undefined : json['mealplanID'],
        'tasteID': !exists(json, 'tasteID') ? undefined : json['tasteID'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function ControllersEatinghistoryToJSON(value?: ControllersEatinghistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addedTime': value.addedTime,
        'foodmenuID': value.foodmenuID,
        'mealplanID': value.mealplanID,
        'tasteID': value.tasteID,
        'userID': value.userID,
    };
}


