/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntFoodmenuEdges,
    EntFoodmenuEdgesFromJSON,
    EntFoodmenuEdgesFromJSONTyped,
    EntFoodmenuEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFoodmenu
 */
export interface EntFoodmenu {
    /**
     * 
     * @type {EntFoodmenuEdges}
     * @memberof EntFoodmenu
     */
    edges?: EntFoodmenuEdges;
    /**
     * FoodmenuName holds the value of the "foodmenu_name" field.
     * @type {string}
     * @memberof EntFoodmenu
     */
    foodmenuName?: string;
    /**
     * FoodmenuType holds the value of the "foodmenu_type" field.
     * @type {string}
     * @memberof EntFoodmenu
     */
    foodmenuType?: string;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntFoodmenu
     */
    id?: number;
}

export function EntFoodmenuFromJSON(json: any): EntFoodmenu {
    return EntFoodmenuFromJSONTyped(json, false);
}

export function EntFoodmenuFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFoodmenu {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntFoodmenuEdgesFromJSON(json['edges']),
        'foodmenuName': !exists(json, 'foodmenu_name') ? undefined : json['foodmenu_name'],
        'foodmenuType': !exists(json, 'foodmenu_type') ? undefined : json['foodmenu_type'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntFoodmenuToJSON(value?: EntFoodmenu | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntFoodmenuEdgesToJSON(value.edges),
        'foodmenu_name': value.foodmenuName,
        'foodmenu_type': value.foodmenuType,
        'id': value.id,
    };
}


