/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEatinghistory,
    EntEatinghistoryFromJSON,
    EntEatinghistoryFromJSONTyped,
    EntEatinghistoryToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMealplanEdges
 */
export interface EntMealplanEdges {
    /**
     * Eatinghistory holds the value of the eatinghistory edge.
     * @type {Array<EntEatinghistory>}
     * @memberof EntMealplanEdges
     */
    eatinghistory?: Array<EntEatinghistory>;
    /**
     * 
     * @type {EntUser}
     * @memberof EntMealplanEdges
     */
    owner?: EntUser;
}

export function EntMealplanEdgesFromJSON(json: any): EntMealplanEdges {
    return EntMealplanEdgesFromJSONTyped(json, false);
}

export function EntMealplanEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMealplanEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eatinghistory': !exists(json, 'eatinghistory') ? undefined : ((json['eatinghistory'] as Array<any>).map(EntEatinghistoryFromJSON)),
        'owner': !exists(json, 'owner') ? undefined : EntUserFromJSON(json['owner']),
    };
}

export function EntMealplanEdgesToJSON(value?: EntMealplanEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eatinghistory': value.eatinghistory === undefined ? undefined : ((value.eatinghistory as Array<any>).map(EntEatinghistoryToJSON)),
        'owner': EntUserToJSON(value.owner),
    };
}


