/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntMealplanEdges,
    EntMealplanEdgesFromJSON,
    EntMealplanEdgesFromJSONTyped,
    EntMealplanEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntMealplan
 */
export interface EntMealplan {
    /**
     * 
     * @type {EntMealplanEdges}
     * @memberof EntMealplan
     */
    edges?: EntMealplanEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntMealplan
     */
    id?: number;
    /**
     * MealplanName holds the value of the "mealplan_name" field.
     * @type {string}
     * @memberof EntMealplan
     */
    mealplanName?: string;
}

export function EntMealplanFromJSON(json: any): EntMealplan {
    return EntMealplanFromJSONTyped(json, false);
}

export function EntMealplanFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntMealplan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntMealplanEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'mealplanName': !exists(json, 'mealplan_name') ? undefined : json['mealplan_name'],
    };
}

export function EntMealplanToJSON(value?: EntMealplan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntMealplanEdgesToJSON(value.edges),
        'id': value.id,
        'mealplan_name': value.mealplanName,
    };
}


