/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntTasteEdges,
    EntTasteEdgesFromJSON,
    EntTasteEdgesFromJSONTyped,
    EntTasteEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTaste
 */
export interface EntTaste {
    /**
     * 
     * @type {EntTasteEdges}
     * @memberof EntTaste
     */
    edges?: EntTasteEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntTaste
     */
    id?: number;
    /**
     * TasteName holds the value of the "taste_name" field.
     * @type {string}
     * @memberof EntTaste
     */
    tasteName?: string;
}

export function EntTasteFromJSON(json: any): EntTaste {
    return EntTasteFromJSONTyped(json, false);
}

export function EntTasteFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTaste {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'edges': !exists(json, 'edges') ? undefined : EntTasteEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'tasteName': !exists(json, 'taste_name') ? undefined : json['taste_name'],
    };
}

export function EntTasteToJSON(value?: EntTaste | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'edges': EntTasteEdgesToJSON(value.edges),
        'id': value.id,
        'taste_name': value.tasteName,
    };
}


