/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEatinghistory,
    EntEatinghistoryFromJSON,
    EntEatinghistoryFromJSONTyped,
    EntEatinghistoryToJSON,
    EntFoodmenu,
    EntFoodmenuFromJSON,
    EntFoodmenuFromJSONTyped,
    EntFoodmenuToJSON,
    EntMealplan,
    EntMealplanFromJSON,
    EntMealplanFromJSONTyped,
    EntMealplanToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * Eatinghistory holds the value of the eatinghistory edge.
     * @type {Array<EntEatinghistory>}
     * @memberof EntUserEdges
     */
    eatinghistory?: Array<EntEatinghistory>;
    /**
     * Foodmenu holds the value of the foodmenu edge.
     * @type {Array<EntFoodmenu>}
     * @memberof EntUserEdges
     */
    foodmenu?: Array<EntFoodmenu>;
    /**
     * Mealplan holds the value of the mealplan edge.
     * @type {Array<EntMealplan>}
     * @memberof EntUserEdges
     */
    mealplan?: Array<EntMealplan>;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eatinghistory': !exists(json, 'eatinghistory') ? undefined : ((json['eatinghistory'] as Array<any>).map(EntEatinghistoryFromJSON)),
        'foodmenu': !exists(json, 'foodmenu') ? undefined : ((json['foodmenu'] as Array<any>).map(EntFoodmenuFromJSON)),
        'mealplan': !exists(json, 'mealplan') ? undefined : ((json['mealplan'] as Array<any>).map(EntMealplanFromJSON)),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eatinghistory': value.eatinghistory === undefined ? undefined : ((value.eatinghistory as Array<any>).map(EntEatinghistoryToJSON)),
        'foodmenu': value.foodmenu === undefined ? undefined : ((value.foodmenu as Array<any>).map(EntFoodmenuToJSON)),
        'mealplan': value.mealplan === undefined ? undefined : ((value.mealplan as Array<any>).map(EntMealplanToJSON)),
    };
}


